#!/usr/bin/env bash
# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# AICR Deployment Script
# Generated by AICR Bundler v1.0.0
#
# Usage: ./deploy.sh [--no-wait] [--best-effort] [--retries N]
#   --no-wait      Skip Helm chart-level wait where AICR uses --wait (keeps --timeout for hooks)
#   --best-effort  Continue past individual component failures (log warnings)
#   --retries N    Retry failed helm/kubectl operations N times with backoff (default: 5, 0 = fail-fast)
#
# This script is optional — each component subdirectory has its own install.sh
# with a single baked-in `helm upgrade --install` command. For detailed behavior
# docs (CRD ordering, async components, error handling), see the AICR CLI Reference:
#   https://github.com/NVIDIA/aicr/blob/main/docs/user/cli-reference.md#deploy-script-behavior-deploysh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Run helm commands from a temp directory to prevent local chart directories
# (e.g., bundle/001-nodewright-operator/) from shadowing remote chart references.
HELM_WORKDIR="$(mktemp -d)"
trap 'rm -rf "${HELM_WORKDIR}"; exit 130' INT TERM
trap 'rm -rf "${HELM_WORKDIR}"' EXIT

HELM_TIMEOUT="10m"
NO_WAIT=false
BEST_EFFORT=false
FAILED_COMPONENTS=""
NEEDS_RETRY=""
MAX_RETRIES=5

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-wait) NO_WAIT=true; shift ;;
    --best-effort) BEST_EFFORT=true; shift ;;
    --retries)
      if [[ $# -lt 2 ]]; then echo "Error: --retries requires a value"; exit 1; fi
      if ! [[ "$2" =~ ^[0-9]+$ ]]; then echo "Error: --retries requires a non-negative integer"; exit 1; fi
      MAX_RETRIES="$2"; shift 2 ;;
    *) echo "Error: unknown option: $1"; echo "Usage: ./deploy.sh [--no-wait] [--best-effort] [--retries N]"; exit 1 ;;
  esac
done

# ==============================================================================
# Kubernetes connection resolution
# ==============================================================================
# Inputs, all optional:
#   KUBE_CONTEXT     context name to act on.
#   KUBECONFIG       path to a kubeconfig. Both helm and kubectl read it from
#                    the environment, so no flag is derived from it.
#   KUBECONFIG_FLAG  deprecated. A literal helm flag string, translated below.
#
# helm and kubectl spell the same connection option differently -- helm's
# --kube-context is kubectl's --context -- so a context resolves to two arrays
# rather than one shared string. Forwarding helm's spelling to kubectl aborts on
# an unknown flag; dropping it silently is worse, because the reads and the
# cluster writes would then land on whatever context the ambient kubeconfig
# names, which is the wrong-cluster write this contract exists to prevent.
#
# An option this contract does not translate is refused rather than guessed at.
#
# Every rejection below exits before the first cluster call. A connection
# option that is merely dropped is indistinguishable from one never set, and
# the fallback is the ambient context.
#
# Both arrays are always declared, but a given script calls only one of the two
# binaries, so the other is legitimately unread here.
# shellcheck disable=SC2034
HELM_CONN=()
# shellcheck disable=SC2034
KUBECTL_CONN=()

# Records the kubeconfig the deprecated flag names. A value disagreeing with an
# existing KUBECONFIG selects a different cluster exactly as two contexts would,
# so it is refused on the same grounds rather than silently overwritten.
#
# Exported as well as passed: bash cannot export an array, and the deprecated
# variable is unset once translated, so a child script re-running this prologue
# would otherwise see no kubeconfig and fall back to the ambient one.
# Records the context the deprecated flag names. Repeats are allowed only while
# they agree: each occurrence used to overwrite the last, so the final value
# won silently and every later helm and kubectl call -- including the CRD
# writes and the taint removal -- acted on it.
_aicr_check_context() {
  if [[ -n "${_aicr_ctx}" && "${_aicr_ctx}" != "$1" ]]; then
    echo "ERROR: KUBECONFIG_FLAG names context '${_aicr_ctx}' and then '$1'." >&2
    echo "       Refusing to guess which cluster to act on; name it once." >&2
    exit 1
  fi
  _aicr_ctx="$1"
}

# $1 is the path; the remaining arguments are the argv form to forward, so the
# caller's spelling (--kubeconfig PATH or --kubeconfig=PATH) reaches the
# binaries unchanged.
_aicr_check_kubeconfig() {
  _aicr_kc="$1"
  shift
  if [[ -n "${KUBECONFIG:-}" && "${KUBECONFIG}" != "${_aicr_kc}" ]]; then
    echo "ERROR: KUBECONFIG names '${KUBECONFIG}' but KUBECONFIG_FLAG names" >&2
    echo "       '${_aicr_kc}'. Refusing to guess which cluster to act on; set" >&2
    echo "       only KUBECONFIG." >&2
    exit 1
  fi
  KUBECONFIG="${_aicr_kc}"
  export KUBECONFIG
  HELM_CONN+=("$@")
  KUBECTL_CONN+=("$@")
}

if [[ -n "${KUBECONFIG_FLAG:-}" ]]; then
  echo "WARNING: KUBECONFIG_FLAG is deprecated; export KUBE_CONTEXT (and KUBECONFIG) instead." >&2

  # Deliberate word-split: this slot holds a flag list, not a single word.
  # Globbing is suppressed around it because the same unquoted expansion also
  # performs pathname expansion, and a kubeconfig path is a value rather than a
  # pattern: one match for /tmp/kc*.yaml silently substitutes a different file,
  # and several append tokens that are then rejected as unsupported options.
  # Restored only if this shell had it enabled, so an embedding script that
  # deliberately runs with `set -f` keeps it.
  _aicr_reglob=0
  [[ -o noglob ]] || { _aicr_reglob=1; set -f; }
  # shellcheck disable=SC2206
  _aicr_argv=(${KUBECONFIG_FLAG})
  (( _aicr_reglob == 0 )) || set +f
  _aicr_i=0
  _aicr_n=${#_aicr_argv[@]}
  _aicr_ctx=""

  # Indexed rather than reslicing: `arr=("${arr[@]:2}")` expands to nothing on
  # the final pair, and bash 3.2 -- which stock macOS still ships -- errors on
  # an empty array expansion under `set -u`.
  while (( _aicr_i < _aicr_n )); do
    _aicr_tok="${_aicr_argv[_aicr_i]}"
    case "${_aicr_tok}" in
      --kube-context|--kubeconfig)
        if (( _aicr_i + 1 >= _aicr_n )); then
          echo "ERROR: KUBECONFIG_FLAG ends with ${_aicr_tok} and no value." >&2
          exit 1
        fi
        _aicr_val="${_aicr_argv[_aicr_i+1]}"
        # Another option where the value belongs means the value was omitted.
        # Accepting it would name a flag as the context or the kubeconfig path,
        # and the resulting lookup failure is not the error the operator would
        # read as "you forgot a value".
        # Names the offending option, never its argument, for the same reason
        # the catch-all below does.
        if [[ "${_aicr_val}" == --* ]]; then
          echo "ERROR: KUBECONFIG_FLAG gives ${_aicr_tok} the value" >&2
          echo "       '${_aicr_val%%=*}', which is another option rather than a value." >&2
          exit 1
        fi
        if [[ "${_aicr_tok}" == "--kube-context" ]]; then
          _aicr_check_context "${_aicr_val}"
        else
          _aicr_check_kubeconfig "${_aicr_val}" --kubeconfig "${_aicr_val}"
        fi
        _aicr_i=$(( _aicr_i + 2 ))
        ;;
      --kube-context=*|--kubeconfig=*)
        _aicr_val="${_aicr_tok#*=}"
        if [[ -z "${_aicr_val}" ]]; then
          echo "ERROR: KUBECONFIG_FLAG carries '${_aicr_tok}', whose value is empty." >&2
          exit 1
        fi
        if [[ "${_aicr_tok}" == --kube-context=* ]]; then
          _aicr_check_context "${_aicr_val}"
        else
          _aicr_check_kubeconfig "${_aicr_val}" "${_aicr_tok}"
        fi
        _aicr_i=$(( _aicr_i + 1 ))
        ;;
      # Names the option, never its argument. helm's --kube-token carries a
      # bearer token in the joined form, and these scripts run with their output
      # attached to the terminal and to CI logs, then get retried. kubectl
      # reports an unknown flag by name alone, so echoing the whole token here
      # would disclose what the unpatched path did not.
      #
      # The rejected options do have kubectl equivalents -- --kube-token is
      # --token, --kube-apiserver is --server -- so this is a scope boundary,
      # not an unknown mapping.
      *)
        echo "ERROR: KUBECONFIG_FLAG carries '${_aicr_tok%%=*}', which this" >&2
        echo "       contract does not support; it translates only" >&2
        echo "       --kube-context and --kubeconfig. It stops here rather than" >&2
        echo "       act on an unintended cluster. Export KUBE_CONTEXT instead." >&2
        exit 1
        ;;
    esac
  done

  if [[ -n "${_aicr_ctx}" ]]; then
    if [[ -n "${KUBE_CONTEXT:-}" && "${KUBE_CONTEXT}" != "${_aicr_ctx}" ]]; then
      echo "ERROR: KUBE_CONTEXT names '${KUBE_CONTEXT}' but KUBECONFIG_FLAG names" >&2
      echo "       '${_aicr_ctx}'. Refusing to guess which cluster to act on;" >&2
      echo "       set only KUBE_CONTEXT." >&2
      exit 1
    fi
    KUBE_CONTEXT="${_aicr_ctx}"
  fi

  # Children resolve from the normalized variables, so the deprecated spelling
  # stops here rather than being re-parsed (and re-warned) once per script.
  unset KUBECONFIG_FLAG
fi

if [[ -n "${KUBE_CONTEXT:-}" ]]; then
  export KUBE_CONTEXT
  HELM_CONN+=(--kube-context "${KUBE_CONTEXT}")
  KUBECTL_CONN+=(--context "${KUBE_CONTEXT}")
fi

# Remediation commands printed below are meant to be copy-pasted, so they carry
# the same connection this script acts on rather than whatever the reader's
# ambient kubeconfig happens to select. Several of those commands delete
# webhooks, APIServices, or CRDs, so a hint that silently resolves elsewhere
# is worse than no hint.
#
# Both halves of the selection are carried, not just the context: a cluster
# chosen through KUBECONFIG alone has an empty KUBE_CONTEXT, and a hint
# naming neither would target the reader's ambient cluster. printf %q escapes
# each value as one shell word, so a path or context containing whitespace or
# shell syntax survives the copy-paste as a single argument.
#
# The kubeconfig rides as the variable rather than as --kubeconfig, because
# KUBECONFIG is a :-separated merge list while the flag takes a single file:
# handed a list, kubectl resolves an empty config and still exits 0, so the
# remedy would find nothing and report no error. Assigning the variable is
# correct for both the single-file and the merged case.
KUBECONFIG_PREFIX=""
if [[ -n "${KUBECONFIG:-}" ]]; then
  KUBECONFIG_PREFIX="KUBECONFIG=$(printf '%q' "${KUBECONFIG}") "
fi
KUBECTL_HINT="${KUBECONFIG_PREFIX}kubectl"
HELM_HINT="${KUBECONFIG_PREFIX}helm"
# install.sh resolves its own connection from the environment, so its hint
# carries assignments rather than flags.
INSTALL_HINT_ENV="${KUBECONFIG_PREFIX}"
if [[ -n "${KUBE_CONTEXT:-}" ]]; then
  KUBECTL_HINT+=" --context $(printf '%q' "${KUBE_CONTEXT}")"
  HELM_HINT+=" --kube-context $(printf '%q' "${KUBE_CONTEXT}")"
  INSTALL_HINT_ENV+="KUBE_CONTEXT=$(printf '%q' "${KUBE_CONTEXT}") "
fi
# ==============================================================================
# Output helpers (respects NO_COLOR and non-TTY)
# ==============================================================================
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  _G=$'\033[0;32m';_R=$'\033[0;31m';_Y=$'\033[1;33m'
  _B=$'\033[1m';_D=$'\033[2m';_X=$'\033[0m'
else
  _G='';_R='';_Y='';_B='';_D='';_X=''
fi

function _ok()       { printf '%s✓%s %s\n' "${_G}" "${_X}" "$*"; }
function _fail()     { printf '%s✗%s %s\n' "${_R}" "${_X}" "$*"; }
function _warn_line(){ printf '%s⚠%s %s\n' "${_Y}" "${_X}" "$*"; }

function _step_header() {
  local manual_dir
  printf -v manual_dir '%q' "$5"
  printf '\n%s┌─ [%s/%s] %s  →  %s%s\n' "${_B}" "$1" "$2" "$3" "$4" "${_X}"
  # The resolved selection is baked in rather than named as something to set:
  # this line installs, and pasted into a fresh shell without it the release
  # lands on whatever cluster that shell happens to select.
  printf '%s│  Manual (approx, set DRY_RUN_FLAG/COMPONENT_WAIT_ARGS as needed): cd %s && %sbash install.sh%s\n' "${_D}" "${manual_dir}" "${INSTALL_HINT_ENV}" "${_X}"
}

function _step_ok() {
  printf '%s└─ ✓%s %s installed\n' "${_G}" "${_X}" "$1"
}

function _step_fail() {
  printf '%s└─ ✗%s %s FAILED (after %s attempts)\n' "${_R}" "${_X}" "$1" "$2"
}

function _step_retry() {
  printf '%s  ↺%s %s: attempt %s/%s failed, retrying in %ss...\n' "${_Y}" "${_X}" "$1" "$2" "$3" "$4"
}

# Export env vars consumed by each folder's install.sh (rendered by localformat).
# DRY_RUN_FLAG / HELM_DEBUG_FLAG default to empty strings; KUBE_CONTEXT and
# KUBECONFIG are already exported by the connection block above.
export DRY_RUN_FLAG="${DRY_RUN_FLAG:-}"
export HELM_DEBUG_FLAG="${HELM_DEBUG_FLAG:-}"

function helm_failed() {
  if [[ "${BEST_EFFORT}" == "true" ]]; then
    _warn_line "$1 install failed, continuing (--best-effort)"
    FAILED_COMPONENTS="${FAILED_COMPONENTS} $1"
  else
    exit 1
  fi
}

# Compute backoff delay from attempt number (1-indexed).
# Examples: attempt 1→5s, 2→20s, 3→45s, 4→80s, 5→120s (cap)
function backoff_seconds() {
  local attempt=$1
  local seconds=$(( attempt * attempt * 5 ))
  if [[ ${seconds} -gt 120 ]]; then seconds=120; fi
  echo "${seconds}"
}

# Clean up stale Helm hook Jobs before retrying. When a hook Job (e.g.,
# crd-upgrader) times out or fails, it stays in the namespace and blocks
# subsequent install attempts with "Job not ready" errors.
# Helm hooks are identified by the helm.sh/hook *annotation* (not a label),
# so we list all non-succeeded Jobs and check each individually via JSON.
function cleanup_helm_hooks() {
  local namespace="$1"
  local job_names
  job_names=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get jobs -n "${namespace}" \
    --field-selector=status.successful=0 \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' \
    2>/dev/null || true)
  if [[ -z "${job_names}" ]]; then
    return
  fi
  while IFS= read -r name; do
    [[ -z "${name}" ]] && continue
    # Get the full Job JSON to reliably check annotations and status
    local job_json
    job_json=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get job "${name}" -n "${namespace}" -o json 2>/dev/null || true)
    [[ -z "${job_json}" ]] && continue
    # Skip non-hook Jobs (no helm.sh/hook annotation)
    local hook_val
    hook_val=$(echo "${job_json}" | grep -o '"helm.sh/hook"' || true)
    [[ -z "${hook_val}" ]] && continue
    # Capture diagnostics before deleting. This helps diagnose transient hook
    # failures (e.g., dynamo ssh-keygen) that are otherwise lost after cleanup.
    echo "  --- Failed hook Job ${name} diagnostics ---"
    kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} describe job "${name}" -n "${namespace}" 2>/dev/null | tail -50 || true
    local pod_names
    pod_names=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get pods -n "${namespace}" -l "job-name=${name}" \
      -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null || true)
    for pod_name in ${pod_names}; do
      echo "  --- Hook pod ${pod_name} describe ---"
      kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} describe pod "${pod_name}" -n "${namespace}" 2>/dev/null | tail -50 || true
    done
    echo "  --- End diagnostics for ${name} ---"
    # Delete any non-succeeded hook Job. This function only runs after a Helm
    # failure, so any hook Job without a successful completion is blocking the
    # retry — whether it failed, is stuck Pending (timed out before the pod
    # started), or is still active with a stuck container.
    echo "  Cleaning up stale Helm hook Job ${name} in ${namespace}..."
    kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} delete job "${name}" -n "${namespace}" --ignore-not-found 2>/dev/null || true
  done <<< "${job_names}"
}

function dump_kai_scheduler_helm_diagnostics() {
  local namespace="$1"
  if [[ "${namespace}" != "kai-scheduler" ]]; then
    return
  fi

  echo "  --- ${namespace} diagnostics ---"
  echo "  Jobs:"
  kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get jobs -n "${namespace}" 2>/dev/null || true
  echo "  Job descriptions:"
  kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} describe jobs -n "${namespace}" 2>/dev/null || true
  echo "  Pods:"
  kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get pods -n "${namespace}" -o wide 2>/dev/null || true
  echo "  Pod descriptions:"
  kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} describe pods -n "${namespace}" 2>/dev/null || true
  echo "  Recent events:"
  kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get events -n "${namespace}" --sort-by='.lastTimestamp' 2>/dev/null | tail -30 || true
  echo "  --- End ${namespace} diagnostics ---"
}

# Components that use operator patterns with custom resources that reconcile
# asynchronously. Helm --wait may time out waiting for CR readiness even though
# all pods start successfully. These components are installed without --wait.
ASYNC_COMPONENTS="kai-scheduler"

# ==============================================================================
# Pre-flight checks
# ==============================================================================
# Verify the cluster is clean before deploying. Stale webhooks, terminating
# namespaces, and orphaned API services from a previous install can block pod
# creation and namespace deletion, causing silent deployment failures.

printf '\n%s══ Pre-flight checks ══════════════════════════════════════════════%s\n' "${_B}" "${_X}"

preflight_failed=false

# Bundle namespace list (deduplicated)
BUNDLE_NAMESPACES=$(echo "skyhook " | tr ' ' '\n' | sort -u | tr '\n' ' ')

# Check for terminating namespaces that overlap with our components
for ns in ${BUNDLE_NAMESPACES}; do
  phase=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get ns "${ns}" -o jsonpath='{.status.phase}' 2>/dev/null || true)
  if [[ "${phase}" == "Terminating" ]]; then
    echo "ERROR: namespace '${ns}' is still terminating from a previous install."
    echo "  Wait for it to finish, or force-finalize with:"
    echo "    ${KUBECTL_HINT} get ns ${ns} -o json | jq '.spec.finalizers=[]' | ${KUBECTL_HINT} replace --raw /api/v1/namespaces/${ns}/finalize -f -"
    preflight_failed=true
  fi
done

# Check for stale webhooks whose backing services no longer exist.
# Scoped to bundle namespaces only to avoid false positives from unrelated
# platform webhooks in shared clusters.
if command -v jq &>/dev/null; then
  for kind in mutatingwebhookconfigurations validatingwebhookconfigurations; do
    while IFS=$'\t' read -r wh_name svc_ns svc_name; do
      # Only check webhooks pointing to our bundle namespaces
      is_bundle_ns=false
      for ns in ${BUNDLE_NAMESPACES}; do
        [[ "${svc_ns}" == "${ns}" ]] && is_bundle_ns=true && break
      done
      [[ "${is_bundle_ns}" == "false" ]] && continue

      # Use explicit NotFound check to avoid false positives from transient errors
      svc_check=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get svc "${svc_name}" -n "${svc_ns}" 2>&1) || true
      if echo "${svc_check}" | grep -q "NotFound\|not found"; then
        echo "ERROR: ${kind} '${wh_name}' references non-existent service ${svc_ns}/${svc_name}."
        echo "  This will block pod/resource creation. Delete with: ${KUBECTL_HINT} delete ${kind} ${wh_name}"
        preflight_failed=true
      fi
    done < <(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get "${kind}" -o json 2>/dev/null | \
      jq -r '.items[] | .metadata.name as $wh | .webhooks[]? | select(.clientConfig.service != null) | [$wh, .clientConfig.service.namespace, .clientConfig.service.name] | @tsv' 2>/dev/null || true)
  done
else
  echo "NOTE: jq not found — skipping webhook pre-flight checks. Install jq for full pre-flight validation."
fi

# Check for stale API services (e.g., custom.metrics.k8s.io from prometheus-adapter)
if command -v jq &>/dev/null; then
  for api_svc in $(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get apiservices -o json 2>/dev/null | jq -r '.items[] | select(.status.conditions[]? | .type == "Available" and .status == "False") | .metadata.name' 2>/dev/null || true); do
    echo "WARNING: API service '${api_svc}' is unavailable. This can block namespace deletion."
    echo "  Delete with: ${KUBECTL_HINT} delete apiservice ${api_svc}"
    # API service issues are warnings, not hard failures — they don't block deployment directly
  done
else
  echo "NOTE: jq not found — skipping API service pre-flight checks."
fi

# Check for orphaned CRDs from previous deployments.
# Scoped to CRD groups belonging to components in this bundle to avoid
# false positives from unrelated platform installs on shared clusters.
ORPHANED_CRD_GROUPS=""
for group in ${ORPHANED_CRD_GROUPS}; do
  orphaned=$(kubectl ${KUBECTL_CONN[@]+"${KUBECTL_CONN[@]}"} get crd -o name 2>/dev/null | grep "\.${group}$" || true)
  if [[ -n "${orphaned}" ]]; then
    echo "WARNING: orphaned CRDs from previous deployment: ${orphaned}"
    echo "  These may cause conflicts. Delete with: ${KUBECTL_HINT} delete ${orphaned}"
  fi
done

# Check for stale nodewright node taints from a previous deployment.
# Only remove taints if nodewright-operator is NOT already running (i.e., fresh deploy).
# If the operator is running, taints are legitimate scheduling guards.

if [[ "${preflight_failed}" == "true" ]]; then
  echo ""
  _fail "Pre-flight checks failed. Fix the issues above before deploying."
  echo "  To clean up partial state, run '${HELM_HINT} uninstall <release> -n <namespace>' for each affected component, then retry."
  exit 1
fi

_ok "Pre-flight checks passed"
printf '\n%s══ Deploying AICR components ══════════════════════════════════════%s\n' "${_B}" "${_X}"

# ==============================================================================
# Install loop
# ==============================================================================
# Generic install loop. Each folder's install.sh is rendered by localformat
# with the right helm command baked in — deploy.sh has no per-component
# knowledge here. Per-component special-case logic (async wait, DRA plugin
# restart) runs in the post-install blocks below, matched by component name.
cd "${HELM_WORKDIR}"

# Pre-count folders for accurate [N/M] progress display.
TOTAL_STEPS=0
for _d in "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/; do
  [[ -d "${_d}" ]] && TOTAL_STEPS=$((TOTAL_STEPS+1))
done

STEP=0

for dir in "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/; do
  [[ -d "${dir}" ]] || continue
  dir="${dir%/}"
  base="${dir##*/}"
  name="${base#[0-9][0-9][0-9]-}"
  STEP=$((STEP+1))
  # Source the namespace from the folder's install.sh — not the folder
  # basename — because the helm release name and its target namespace can
  # differ (e.g. nodewright-operator → namespace skyhook; gpu-operator-post →
  # namespace gpu-operator). cleanup_helm_hooks and the kai diagnostics
  # both operate on the namespace.
  namespace=$(awk '{ for (i=1;i<NF;i++) if ($i=="--namespace") { print $(i+1); exit } }' "${dir}/install.sh")
  _step_header "${STEP}" "${TOTAL_STEPS}" "${name}" "${namespace}" "${dir}"
  # Derive wait args: global --wait/--no-wait behavior + per-component timeout.
  COMPONENT_HELM_TIMEOUT="${HELM_TIMEOUT}"
  COMPONENT_MAX_RETRIES="${MAX_RETRIES}"
  COMPONENT_WAIT_ARGS=""
  case "${name}" in
    kai-scheduler)
      COMPONENT_HELM_TIMEOUT="20m"
      COMPONENT_MAX_RETRIES="1"
      ;;
    *-readiness)
      # Readiness gate folders run the gate CLI as a post-install/post-upgrade
      # helm hook Job that polls component signals until they pass or the gate's
      # own --max-wait deadline elapses. Helm --wait blocks on hook completion
      # regardless of --wait-for-jobs, so only --timeout is needed here.
      # The gate owns the deadline; helm cannot wait indefinitely (--wait is
      # bounded by --timeout), so this --timeout is DERIVED by the bundler as
      # gate --max-wait + a buffer — large enough that helm never preempts the
      # gate, small enough to still surface a hung gate shortly after. The gate
      # is a correctness barrier, so it ignores --no-wait and pins its args:
      #   MAX_RETRIES=1    the gate owns its own poll/retry loop; re-running the
      #                    whole Job on a transient helm error only doubles wait.
      COMPONENT_HELM_TIMEOUT="1h35m0s"
      COMPONENT_MAX_RETRIES="1"
      COMPONENT_WAIT_ARGS="--wait --timeout ${COMPONENT_HELM_TIMEOUT}"
      ;;
  esac
  # Components that didn't pin their own wait args above honor the global
  # --wait/--no-wait flag plus the async-component override.
  if [[ -z "${COMPONENT_WAIT_ARGS}" ]]; then
    if [[ "${NO_WAIT}" == "true" ]]; then
      COMPONENT_WAIT_ARGS="--timeout ${COMPONENT_HELM_TIMEOUT}"
    else
      COMPONENT_WAIT_ARGS="--wait --timeout ${COMPONENT_HELM_TIMEOUT}"
    fi
    if echo "${ASYNC_COMPONENTS}" | grep -qw "${name}"; then
      # Skip --wait (no readiness check) but keep --timeout for hook completion.
      COMPONENT_WAIT_ARGS="--timeout ${COMPONENT_HELM_TIMEOUT}"
      printf '%s│%s  (async component — skipping --wait, keeping --timeout for hooks)\n' "${_D}" "${_X}"
    fi
  fi
  export COMPONENT_WAIT_ARGS

  # Invoke the per-folder install.sh with retry. On failure, dump kai-scheduler
  # diagnostics and clean up stale Helm hook Jobs between attempts.
  attempt=0
  while true; do
    if ( cd "${dir}" && bash install.sh ); then
      _step_ok "${name}"
      break
    fi

    attempt=$((attempt + 1))
    dump_kai_scheduler_helm_diagnostics "${namespace}"

    if [[ ${attempt} -gt ${COMPONENT_MAX_RETRIES} ]]; then
      _step_fail "${name}" "${attempt}"
      helm_failed "${name}"
      break
    fi

    cleanup_helm_hooks "${namespace}"

    wait_secs=$(backoff_seconds "${attempt}")

    _step_retry "${name}" "${attempt}" "${COMPONENT_MAX_RETRIES}" "${wait_secs}"

    sleep "${wait_secs}"
  done

  # --- post-install name-matched blocks ---
done

if [[ -n "${FAILED_COMPONENTS}" ]]; then
  _fail "Deployment completed with failures (--best-effort):${FAILED_COMPONENTS}"
else
  _ok "All components installed successfully."
fi
if [[ -n "${NEEDS_RETRY}" ]]; then
  # Distinct from FAILED_COMPONENTS/helm_failed so --best-effort semantics
  # are unaffected: helm itself succeeded, but the DRA kubelet-plugin
  # restart was deliberately withheld because the driver-migration gate
  # was not yet observable when this deploy ran (see the WARNING above).
  # Surfaced with its own non-zero exit below so automated callers (UAT,
  # ArgoCD hooks, CI) get an actionable non-success signal instead of
  # reading "All components installed successfully." as fully done.
  _warn_line "DRA kubelet plugin restart blocked, retry needed for:${NEEDS_RETRY} — re-run this deploy once the operator has converged (driver DaemonSet present or a node carries nvidia.com/gpu.deploy.driver=true)."
fi
echo
echo "NOTE: The above status reflects Helm install and manifest apply results,"
echo "not whether the cluster is ready for GPU workloads. On fresh"
echo "GPU nodes, cluster convergence may continue asynchronously after this"
echo "script exits. Full workload readiness can take additional time for:"
echo "  - node tuning (e.g., Nodewright, ~10-20 min on fresh nodes)"
echo "  - GPU operator operand rollout (driver, toolkit, device-plugin DS)"
echo "  - NVIDIA DRA kubelet plugin registration"
echo
echo "See: https://github.com/NVIDIA/aicr/blob/main/docs/user/cli-reference.md#deploy-script-behavior-deploysh"

# A hard component failure outranks the retry signal: re-running the
# deploy won't fix a broken component, so don't report it as "retry".
if [[ -n "${FAILED_COMPONENTS}" && -n "${NEEDS_RETRY}" ]]; then
  exit 1
fi
if [[ -n "${NEEDS_RETRY}" ]]; then
  exit 2
fi
