// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aicr_test

import (
	"context"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/NVIDIA/aicr/pkg/bundler/checksum"
	aicr "github.com/NVIDIA/aicr/pkg/client/v1"
)

// newVerifyClient returns an embedded-source Client for verification tests.
func newVerifyClient(t *testing.T) *aicr.Client {
	t.Helper()
	client, err := aicr.NewClient(aicr.WithRecipeSource(aicr.EmbeddedSource()))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}
	t.Cleanup(func() { _ = client.Close() })
	return client
}

// newClosedClient returns a Client that has already been closed, for the
// closed-Client guard assertions.
func newClosedClient(t *testing.T) *aicr.Client {
	t.Helper()
	client, err := aicr.NewClient(aicr.WithRecipeSource(aicr.EmbeddedSource()))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}
	if err := client.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	return client
}

// newChecksumBundle writes a minimal bundle whose checksums.txt is generated by
// the same code path real bundle creation uses. It carries no attestation, so
// it verifies to trust level "unverified" — the highest level it can achieve.
func newChecksumBundle(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()

	files := map[string]string{
		"recipe.yaml":              "apiVersion: v1\nkind: Recipe\n",
		"gpu-operator/values.yaml": "driver:\n  version: 570.86.16\n",
	}
	paths := make([]string, 0, len(files))
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
		paths = append(paths, path)
	}
	if err := checksum.GenerateChecksums(context.Background(), dir, paths); err != nil {
		t.Fatalf("GenerateChecksums: %v", err)
	}
	return dir
}

// TestVerifyBundle_ChecksumsOnlyBundle exercises the happy path end to end: an
// unattested but checksum-valid bundle verifies, reports its trust level, and
// satisfies the default policy because the default floor is the highest level
// the bundle could reach.
func TestVerifyBundle_ChecksumsOnlyBundle(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	got, err := client.VerifyBundle(context.Background(), newChecksumBundle(t), aicr.BundleVerifyOptions{})
	if err != nil {
		t.Fatalf("VerifyBundle: %v", err)
	}
	if got.Report == nil {
		t.Fatal("Report is nil on a successful verification")
	}
	if !got.Report.ChecksumsPassed {
		t.Errorf("ChecksumsPassed = false, want true (errors: %v)", got.Report.Errors)
	}
	if got.Report.ChecksumFiles != 2 {
		t.Errorf("ChecksumFiles = %d, want 2", got.Report.ChecksumFiles)
	}
	if got.PolicyFailure != "" {
		t.Errorf("PolicyFailure = %q, want empty under the default max floor", got.PolicyFailure)
	}
}

// TestVerifyBundle_EmptyMinTrustLevelMeansMax pins the deliberate departure
// from verifier.Policy, where an empty MinTrustLevel skips the trust check.
// The facade treats empty as "max" so a caller who never considered the trust
// floor still gets a gate. Both halves matter: empty must agree with an
// explicit "max", and it must NOT behave like "no check at all".
func TestVerifyBundle_EmptyMinTrustLevelMeansMax(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	dir := newChecksumBundle(t)

	implicit, err := client.VerifyBundle(context.Background(), dir, aicr.BundleVerifyOptions{})
	if err != nil {
		t.Fatalf("VerifyBundle (implicit): %v", err)
	}
	explicit, err := client.VerifyBundle(context.Background(), dir, aicr.BundleVerifyOptions{MinTrustLevel: "max"})
	if err != nil {
		t.Fatalf("VerifyBundle (explicit max): %v", err)
	}
	if implicit.PolicyFailure != explicit.PolicyFailure {
		t.Errorf("implicit PolicyFailure = %q, explicit max = %q; empty must mean max",
			implicit.PolicyFailure, explicit.PolicyFailure)
	}

	// "unknown" is the floor every bundle clears, so it is the observable
	// difference between "max" and a genuinely disabled check. Tamper the
	// bundle so its actual level drops below its max achievable: under the
	// default floor that must fail, under "unknown" it must pass.
	tampered := newChecksumBundle(t)
	if writeErr := os.WriteFile(filepath.Join(tampered, "recipe.yaml"), []byte("tampered\n"), 0o600); writeErr != nil {
		t.Fatalf("tamper: %v", writeErr)
	}

	strict, err := client.VerifyBundle(context.Background(), tampered, aicr.BundleVerifyOptions{})
	if err != nil {
		t.Fatalf("VerifyBundle (tampered, default floor): %v", err)
	}
	if strict.PolicyFailure == "" && len(strict.Report.Errors) == 0 {
		t.Error("tampered bundle passed under the default floor; empty MinTrustLevel is not gating")
	}

	relaxed, err := client.VerifyBundle(context.Background(), tampered, aicr.BundleVerifyOptions{MinTrustLevel: "unknown"})
	if err != nil {
		t.Fatalf("VerifyBundle (tampered, unknown floor): %v", err)
	}
	if relaxed.PolicyFailure != "" {
		t.Errorf("PolicyFailure = %q, want empty: every bundle clears the unknown floor", relaxed.PolicyFailure)
	}
}

// TestVerifyBundle_PolicyFailureIsData locks in that an unmet policy is
// reported through the returned value rather than as an error, so a caller can
// still render the full report explaining why the bundle fell short.
func TestVerifyBundle_PolicyFailureIsData(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	got, err := client.VerifyBundle(context.Background(), newChecksumBundle(t),
		aicr.BundleVerifyOptions{MinTrustLevel: "verified"})
	if err != nil {
		t.Fatalf("VerifyBundle returned an error for a policy failure; want the failure as data: %v", err)
	}
	if got.PolicyFailure == "" {
		t.Fatal("PolicyFailure is empty; an unattested bundle cannot meet the verified floor")
	}
	if got.Report == nil {
		t.Fatal("Report is nil; the report must survive a policy failure")
	}
	if !strings.Contains(got.PolicyFailure, "verified") {
		t.Errorf("PolicyFailure = %q, want it to name the required level", got.PolicyFailure)
	}
}

// TestVerifyBundle_UnparseablePolicyIsAnError separates a caller input fault
// (a trust level that does not exist) from a bundle that simply failed policy.
func TestVerifyBundle_UnparseablePolicyIsAnError(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	_, err := client.VerifyBundle(context.Background(), newChecksumBundle(t),
		aicr.BundleVerifyOptions{MinTrustLevel: "extremely-trusted"})
	wantInvalidRequest(t, err)
}

// TestVerifyBundle_Guards covers every rejection that happens before any
// verification work runs.
func TestVerifyBundle_Guards(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	closed := newClosedClient(t)
	dir := newChecksumBundle(t)

	tests := []struct {
		name   string
		client *aicr.Client
		ctx    context.Context //nolint:containedctx // table-driven guard inputs
		dir    string
		opts   aicr.BundleVerifyOptions
	}{
		{name: "nil client", client: nil, ctx: context.Background(), dir: dir},
		{name: "nil context", client: client, ctx: nil, dir: dir},
		{name: "empty bundle dir", client: client, ctx: context.Background(), dir: ""},
		{name: "closed client", client: closed, ctx: context.Background(), dir: dir},
		{
			name: "ignore tlog without key", client: client, ctx: context.Background(), dir: dir,
			opts: aicr.BundleVerifyOptions{IgnoreTLog: true},
		},
		{
			name: "identity pattern outside NVIDIA/aicr", client: client, ctx: context.Background(), dir: dir,
			opts: aicr.BundleVerifyOptions{CertificateIdentityRegexp: "^https://github.com/evil/repo/.*"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := tt.client.VerifyBundle(tt.ctx, tt.dir, tt.opts)
			wantInvalidRequest(t, err)
		})
	}
}

// TestVerifyBundle_MissingBundleDirIsAnError confirms an unreadable bundle is
// an operational failure, not a verdict.
func TestVerifyBundle_MissingBundleDirIsAnError(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	if _, err := client.VerifyBundle(context.Background(),
		filepath.Join(t.TempDir(), "does-not-exist"), aicr.BundleVerifyOptions{}); err == nil {
		t.Error("expected an error for a missing bundle directory")
	}
}

// TestVerifyEvidence_Guards covers the pre-work rejections. The verification
// path itself needs a registry or a materialized bundle, which is exercised in
// pkg/evidence/verifier.
func TestVerifyEvidence_Guards(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	closed := newClosedClient(t)

	tests := []struct {
		name   string
		client *aicr.Client
		ctx    context.Context //nolint:containedctx // table-driven guard inputs
		opts   aicr.EvidenceVerifyOptions
	}{
		{name: "nil client", client: nil, ctx: context.Background(), opts: aicr.EvidenceVerifyOptions{Input: "./b"}},
		{name: "nil context", client: client, ctx: nil, opts: aicr.EvidenceVerifyOptions{Input: "./b"}},
		{name: "empty input", client: client, ctx: context.Background()},
		{name: "closed client", client: closed, ctx: context.Background(), opts: aicr.EvidenceVerifyOptions{Input: "./b"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := tt.client.VerifyEvidence(tt.ctx, tt.opts)
			wantInvalidRequest(t, err)
		})
	}
}

// TestVerifyCatalog_Guards covers the pre-work rejections. A successful verify
// needs the release Sigstore bundle, which is not in-tree.
func TestVerifyCatalog_Guards(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	closed := newClosedClient(t)

	tests := []struct {
		name   string
		client *aicr.Client
		ctx    context.Context //nolint:containedctx // table-driven guard inputs
		path   string
		opts   aicr.CatalogVerifyOptions
	}{
		{name: "nil client", client: nil, ctx: context.Background(), path: "b.json"},
		{name: "nil context", client: client, ctx: nil, path: "b.json"},
		{name: "empty bundle path", client: client, ctx: context.Background(), path: ""},
		{name: "closed client", client: closed, ctx: context.Background(), path: "b.json"},
		{
			name: "identity pattern outside NVIDIA/aicr", client: client, ctx: context.Background(), path: "b.json",
			opts: aicr.CatalogVerifyOptions{CertificateIdentityRegexp: "^https://github.com/evil/repo/.*"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := tt.client.VerifyCatalog(tt.ctx, tt.path, tt.opts)
			wantInvalidRequest(t, err)
		})
	}
}

// TestVerifyCatalog_MissingBundleIsAnError exercises the delegation path — the
// Client's DataProvider is bound, the digest is recomputed, and the failure to
// read the Sigstore bundle surfaces as a coded error rather than a nil result.
func TestVerifyCatalog_MissingBundleIsAnError(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	got, err := client.VerifyCatalog(context.Background(),
		filepath.Join(t.TempDir(), "recipe-catalog.sigstore.json"), aicr.CatalogVerifyOptions{})
	if err == nil {
		t.Fatalf("expected an error for a missing Sigstore bundle; got %+v", got)
	}
	if got != nil {
		t.Errorf("result = %+v, want nil alongside the error", got)
	}
}

// TestVerifyEvidence_EmptyDirectoryIsAnError exercises the delegation path
// against a local directory input, so no registry is contacted.
func TestVerifyEvidence_EmptyDirectoryIsAnError(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	got, err := client.VerifyEvidence(context.Background(),
		aicr.EvidenceVerifyOptions{Input: t.TempDir()})
	// The verifier may report an unreadable bundle either as an error or as
	// an incomplete verdict; both are correct, and neither may be a silent
	// pass. What must never happen is a "valid" verdict on an empty dir.
	if err == nil && got != nil && got.Exit == aicr.EvidenceExitValidPassed {
		t.Fatal("an empty directory verified as a valid evidence bundle")
	}
}

// TestRecipeDigest_IsDeterministicHex verifies the digest is produced against
// the Client's own catalog and is stable across calls — the property a CI
// drift gate depends on.
func TestRecipeDigest_IsDeterministicHex(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "recipe.yaml")
	if err := os.WriteFile(path, []byte("kind: RecipeResult\napiVersion: aicr.run/v1alpha2\n"), 0o600); err != nil {
		t.Fatalf("write recipe: %v", err)
	}

	client := newVerifyClient(t)
	first, err := client.RecipeDigest(context.Background(), aicr.RecipeDigestOptions{Path: path})
	if err != nil {
		t.Fatalf("RecipeDigest: %v", err)
	}
	if !regexp.MustCompile(`^[0-9a-f]{64}$`).MatchString(first) {
		t.Fatalf("RecipeDigest = %q, want lowercase hex sha256", first)
	}
	second, err := client.RecipeDigest(context.Background(), aicr.RecipeDigestOptions{Path: path})
	if err != nil {
		t.Fatalf("RecipeDigest (repeat): %v", err)
	}
	if first != second {
		t.Errorf("digest is not deterministic: %q then %q", first, second)
	}
}

// TestRecipeDigest_Guards covers the pre-work rejections.
func TestRecipeDigest_Guards(t *testing.T) {
	t.Parallel()

	client := newVerifyClient(t)
	closed := newClosedClient(t)

	tests := []struct {
		name   string
		client *aicr.Client
		ctx    context.Context //nolint:containedctx // table-driven guard inputs
		opts   aicr.RecipeDigestOptions
	}{
		{name: "nil client", client: nil, ctx: context.Background(), opts: aicr.RecipeDigestOptions{Path: "r.yaml"}},
		{name: "nil context", client: client, ctx: nil, opts: aicr.RecipeDigestOptions{Path: "r.yaml"}},
		{name: "empty path", client: client, ctx: context.Background()},
		{name: "closed client", client: closed, ctx: context.Background(), opts: aicr.RecipeDigestOptions{Path: "r.yaml"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := tt.client.RecipeDigest(tt.ctx, tt.opts)
			wantInvalidRequest(t, err)
		})
	}
}

// TestVerifyBinaryAttestation_Guards covers the package-level entry point's
// rejections. A successful verify needs an NVIDIA-CI-signed attestation over a
// real binary digest, which a `go test` executable cannot satisfy.
func TestVerifyBinaryAttestation_Guards(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		ctx  context.Context //nolint:containedctx // table-driven guard inputs
		opts aicr.BinaryAttestationVerifyOptions
	}{
		{
			name: "nil context", ctx: nil,
			opts: aicr.BinaryAttestationVerifyOptions{Attestation: []byte("{}"), BinaryDigest: []byte{0x01}},
		},
		{
			name: "empty attestation", ctx: context.Background(),
			opts: aicr.BinaryAttestationVerifyOptions{BinaryDigest: []byte{0x01}},
		},
		{
			name: "empty binary digest", ctx: context.Background(),
			opts: aicr.BinaryAttestationVerifyOptions{Attestation: []byte("{}")},
		},
		{
			name: "identity pattern outside NVIDIA/aicr", ctx: context.Background(),
			opts: aicr.BinaryAttestationVerifyOptions{
				Attestation:    []byte("{}"),
				BinaryDigest:   []byte{0x01},
				IdentityRegexp: "^https://github.com/evil/repo/.*",
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := aicr.VerifyBinaryAttestation(tt.ctx, tt.opts)
			wantInvalidRequest(t, err)
		})
	}
}

// TestValidateIdentityPattern mirrors the guard the verify entry points apply
// internally, so callers can pre-validate operator input.
func TestValidateIdentityPattern(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		pattern string
		wantErr bool
	}{
		{name: "trusted default", pattern: aicr.TrustedIdentityPattern},
		{
			name:    "retargeted NVIDIA workflow",
			pattern: `^https://github\.com/NVIDIA/aicr/\.github/workflows/server-kms-e2e\.yaml@.*`,
		},
		{name: "other repository", pattern: `^https://github\.com/evil/repo/.*`, wantErr: true},
		{name: "empty", pattern: "", wantErr: true},
		{name: "match anything", pattern: `.*`, wantErr: true},

		// Widening bypasses. Each carries the required repository prefix, so a
		// substring anchor alone lets them through, but each admits identities
		// outside NVIDIA/aicr — reducing the gate to the OIDC issuer pin, which
		// any GitHub Actions workflow in any repository satisfies.
		{
			name:    "trailing alternation matches anything",
			pattern: `^https://github\.com/NVIDIA/aicr/.*|.*$`,
			wantErr: true,
		},
		{
			name:    "leading alternation matches anything",
			pattern: `.*|https://github.com/NVIDIA/aicr/.*`,
			wantErr: true,
		},
		{
			name:    "alternation to one foreign repository",
			pattern: `https://github.com/NVIDIA/aicr/.*|^https://github\.com/evil/repo/.*`,
			wantErr: true,
		},
		{
			name:    "empty branch inside a group",
			pattern: `(https://github.com/NVIDIA/aicr/|)`,
			wantErr: true,
		},
		{
			// Nested in a group, so the root op is a capture rather than an
			// alternation, and the foreign branch names a repository no fixed
			// canary set can enumerate. Rejected because the pattern does not
			// begin with the repository prefix.
			name:    "nested alternation to a foreign repository",
			pattern: `(https://github.com/NVIDIA/aicr/.*|https://github.com/attacker/isolated/.*)`,
			wantErr: true,
		},
		{
			// Alternatives after the prefix stay valid: every branch is
			// already behind the pin.
			name:    "alternation after the prefix",
			pattern: `^https://github\.com/NVIDIA/aicr/\.github/workflows/(on-tag|release)\.yaml@.*`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if err := aicr.ValidateIdentityPattern(tt.pattern); (err != nil) != tt.wantErr {
				t.Errorf("ValidateIdentityPattern(%q) error = %v, wantErr %v", tt.pattern, err, tt.wantErr)
			}
		})
	}
}

// TestTrustLevels confirms the exported levels cover every value
// BundleVerifyOptions.MinTrustLevel documents.
func TestTrustLevels(t *testing.T) {
	t.Parallel()

	levels := aicr.TrustLevels()
	for _, want := range []string{"verified", "attested", "unverified", "unknown"} {
		found := false
		for _, got := range levels {
			if got == want {
				found = true
			}
		}
		if !found {
			t.Errorf("TrustLevels() = %v, missing %q", levels, want)
		}
	}
}

// TestRenderEvidence_NilResult pins the nil handling on both renderers so a
// caller that skipped the error check cannot panic inside the facade.
func TestRenderEvidence_NilResult(t *testing.T) {
	t.Parallel()

	if _, err := aicr.RenderEvidenceJSON(nil); err == nil {
		t.Error("RenderEvidenceJSON(nil) should return an error")
	}
	if got := aicr.RenderEvidenceMarkdown(nil); got != "" {
		t.Errorf("RenderEvidenceMarkdown(nil) = %q, want empty", got)
	}
}

// TestEvidenceExitConstants pins the re-exported verdicts to their documented
// numeric values: a CI gate branches on these, so a silent renumber upstream
// must fail here.
func TestEvidenceExitConstants(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		got  int
		want int
	}{
		{name: "valid passed", got: aicr.EvidenceExitValidPassed, want: 0},
		{name: "valid with phase failures", got: aicr.EvidenceExitValidPhaseFailures, want: 1},
		{name: "invalid", got: aicr.EvidenceExitInvalid, want: 2},
		{name: "incomplete", got: aicr.EvidenceExitIncomplete, want: 3},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if tt.got != tt.want {
				t.Errorf("verdict = %d, want %d", tt.got, tt.want)
			}
		})
	}
	if aicr.EvidenceCauseCanceled != "canceled" {
		t.Errorf("EvidenceCauseCanceled = %q, want canceled", aicr.EvidenceCauseCanceled)
	}
}
