// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package deployer

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/Masterminds/semver/v3"

	"github.com/NVIDIA/aicr/pkg/defaults"
	"github.com/NVIDIA/aicr/pkg/errors"
	"github.com/NVIDIA/aicr/pkg/recipe"
	"github.com/NVIDIA/aicr/pkg/serializer"
)

// IsSafePathComponent returns true if name is a single path component without
// any separators or parent directory references.
//
// Reject embedded separators so callers can rely on the result being a
// single path element. filepath.IsLocal then handles emptiness, absolute
// paths, parent-directory refs (..), and Windows reserved names — and,
// unlike a substring scan for "..", accepts benign names like "foo..bak".
func IsSafePathComponent(name string) bool {
	if strings.ContainsAny(name, `/\`) {
		return false
	}
	return filepath.IsLocal(name)
}

// SafeJoin joins baseDir and name, then verifies the result is contained
// within baseDir. This prevents path traversal when name comes from
// untrusted input (e.g., component names from recipe data).
func SafeJoin(baseDir, name string) (string, error) {
	if filepath.IsAbs(name) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q is absolute and escapes base directory", name))
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", errors.Wrap(errors.ErrCodeInternal, "failed to resolve base directory", err)
	}
	joined := filepath.Clean(filepath.Join(absBase, name))
	if joined != absBase && !strings.HasPrefix(joined, absBase+string(filepath.Separator)) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q escapes base directory", name))
	}
	return joined, nil
}

// WriteValuesFile writes a values.yaml file with header comment to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func WriteValuesFile(values map[string]any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	var buf strings.Builder
	buf.WriteString("# Generated by AICR\n")
	buf.WriteString("---\n")

	if len(values) > 0 {
		// Deterministic marshal so values files feeding checksums.txt
		// (and thus the bundle attestation) are byte-stable across runs.
		yamlBytes, err := serializer.MarshalYAMLDeterministic(values)
		if err != nil {
			return "", 0, errors.PropagateOrWrap(err, errors.ErrCodeInternal, "failed to marshal values")
		}
		buf.Write(yamlBytes)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write values file", err)
	}

	return outputPath, int64(len(content)), nil
}

// TemplateFuncs is the FuncMap available to every deployer template,
// including those rendered through GenerateFromTemplate.
//
// `q` emits a YAML double-quoted scalar. Quoting matters for any field Helm
// unmarshals as a string: an unquoted `appVersion: 1.2` parses as a float and
// fails the unmarshal, and a value carrying a quote character would break out
// of a hand-written literal. strconv.Quote's escape vocabulary (\", \\, \n,
// \xNN, \uNNNN) is a subset of what YAML's double-quoted style accepts, so
// the result round-trips. Same reasoning as the %q quoting in the argocd-helm
// deployer's Chart.yaml writer (#1034).
//
// `kubeConn` emits the shell prologue documented on KubeConnection.
var TemplateFuncs = template.FuncMap{
	"q":        strconv.Quote,
	"kubeConn": KubeConnection,
}

// GenerateFromTemplate renders a template and writes it to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func GenerateFromTemplate(tmplContent string, data any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	tmpl, err := template.New("template").Funcs(TemplateFuncs).Parse(tmplContent)
	if err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to parse template", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to execute template", err)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write file", err)
	}

	return outputPath, int64(len(content)), nil
}

// NormalizeVersion removes the 'v' prefix from a version string.
// It returns the input unchanged if no prefix is present.
func NormalizeVersion(v string) string {
	return strings.TrimPrefix(v, "v")
}

// NormalizeVersionWithDefault removes the 'v' prefix and defaults empty
// strings to "0.1.0". Use this for Helm chart metadata where a version
// is always required.
func NormalizeVersionWithDefault(v string) string {
	v = strings.TrimPrefix(v, "v")
	if v == "" {
		return "0.1.0"
	}
	return v
}

// NormalizeChartVersion coerces an AICR build version into a value Helm
// accepts for a Chart.yaml `version:` field, stripping the 'v' prefix that
// release tags carry inconsistently.
//
// Helm validates that field as SemVer 2 (chart.Metadata.Validate) and refuses
// to load a chart whose version does not parse. An unstamped build reports
// defaults.DevVersion ("dev"), which does not, so every non-SemVer input —
// "dev", "stock-render-golden", "" — folds to defaults.DevChartVersion rather
// than shipping a chart Helm will reject. Without that fold, `make dev-env`
// and Tilt break on the first `helm install`.
//
// The parse is deliberately the lenient semver.NewVersion rather than
// StrictNewVersion: it is the same call Helm makes when loading a chart, so
// anything returned here will load. (helm lint is stricter and warns on a
// partial version like "1.2"; AICR release tags are always full X.Y.Z, so
// that case is theoretical.)
func NormalizeChartVersion(v string) string {
	v = strings.TrimPrefix(strings.TrimSpace(v), "v")
	if _, err := semver.NewVersion(v); err != nil {
		// The fold is lossy: an unstamped build and a corrupted or
		// hand-edited version both come out as DevChartVersion, so the
		// stamped chart cannot tell them apart afterwards. Erroring here
		// would block bundling over cosmetic metadata, so log instead —
		// but only for the unexpected shapes, since "" and "dev" are the
		// documented sentinels and warning on those would be noise.
		if v != "" && v != defaults.DevVersion {
			slog.Warn("chart version is not SemVer; stamping the dev placeholder instead",
				"version", v, "stamped", defaults.DevChartVersion)
		}
		return defaults.DevChartVersion
	}
	return v
}

// SortByDeploymentOrder sorts items by deployment order using getName to
// extract the component name from each item. Items in the order list are
// sorted by their position; items not in the order list are placed after
// ordered items and sorted alphabetically by name.
func SortByDeploymentOrder[T any](items []T, order []string, getName func(T) string) []T {
	if len(order) == 0 {
		return items
	}

	orderMap := make(map[string]int, len(order))
	for i, name := range order {
		orderMap[name] = i
	}

	sorted := make([]T, len(items))
	copy(sorted, items)

	sort.SliceStable(sorted, func(i, j int) bool {
		nameI := getName(sorted[i])
		nameJ := getName(sorted[j])
		orderI, okI := orderMap[nameI]
		orderJ, okJ := orderMap[nameJ]

		if !okI && !okJ {
			return nameI < nameJ
		}
		if !okI {
			return false
		}
		if !okJ {
			return true
		}
		return orderI < orderJ
	})

	return sorted
}

// SortComponentRefsByDeploymentOrder sorts component refs by deployment order.
func SortComponentRefsByDeploymentOrder(refs []recipe.ComponentRef, order []string) []recipe.ComponentRef {
	return SortByDeploymentOrder(refs, order, func(r recipe.ComponentRef) string { return r.Name })
}

// SortComponentNamesByDeploymentOrder sorts component name strings by deployment order.
func SortComponentNamesByDeploymentOrder(components []string, deploymentOrder []string) []string {
	return SortByDeploymentOrder(components, deploymentOrder, func(s string) string { return s })
}
