// Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/NVIDIA/aicr/pkg/errors"
)

// writeMarkdown renders a human-readable summary: a distinct-host table grouped
// by package type, then the full record list, then the uncovered-source notes.
func writeMarkdown(path string, inv *Inventory) error {
	var b strings.Builder

	b.WriteString("# AICR registry-egress inventory (generated)\n\n")
	b.WriteString("Statically extracted registry/package egress from AICR's structured build & CI sources. ")
	b.WriteString("Generated by `tools/registry-inventory`; do not hand-edit. ")
	b.WriteString("Rendered chart→image pulls are owned by `docs/user/container-images.md` (the BOM) and are not repeated here.\n\n")

	fmt.Fprintf(&b, "- Records: **%d**\n- Distinct hosts: **%d**\n\n", len(inv.Records), len(inv.Hosts))

	b.WriteString("## Distinct hosts\n\n")
	b.WriteString("| Host | Package types | Directions |\n|---|---|---|\n")
	hosts := append([]string(nil), inv.Hosts...)
	sort.Strings(hosts) // render deterministically regardless of caller ordering
	for _, h := range hosts {
		pkgs, dirs := hostFacets(inv, h)
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", h, pkgs, dirs)
	}

	b.WriteString("\n## Records\n\n")
	b.WriteString("| Host | Type | Dir | Consumer | Pin | Detail | Source |\n|---|---|---|---|---|---|---|\n")
	// The many github-action `uses:` refs collapse to one summary row here (they
	// all share the single logical host `github-actions`); the per-ref detail
	// lives in the YAML output.
	ghActions := 0
	for _, r := range inv.Records {
		if r.PackageType == PkgGitHubAction {
			ghActions++
			continue
		}
		pin := r.PinType
		if r.Pin != "" {
			pin = r.PinType + " `" + r.Pin + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | `%s` |\n",
			r.Host, r.PackageType, r.Direction, r.Consumer, pin, mdEscape(r.Detail), r.Source)
	}
	if ghActions > 0 {
		fmt.Fprintf(&b, "| `github-actions` | github-action | pull | ci-runner | per-ref | "+
			"_%d `uses:` refs (see YAML)_ | `.github/**` |\n", ghActions)
	}

	if len(inv.Warnings) > 0 {
		b.WriteString("\n## Warnings\n\n")
		for _, w := range inv.Warnings {
			fmt.Fprintf(&b, "- %s\n", w)
		}
	}

	b.WriteString("\n## Uncovered sources (not statically parsed)\n\n")
	b.WriteString("These egress surfaces are known but not extracted by this prototype — treat the inventory as a floor, not a ceiling:\n\n")
	for _, u := range inv.UncoveredSources {
		fmt.Fprintf(&b, "- %s\n", u)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil { //nolint:gosec // report artifact, not a secret
		return errors.Wrap(errors.ErrCodeInternal, "write "+path, err)
	}
	return nil
}

// hostFacets returns the sorted, comma-joined package types and directions seen
// for a host across all records.
func hostFacets(inv *Inventory, host string) (pkgs, dirs string) {
	ps := map[string]struct{}{}
	ds := map[string]struct{}{}
	for _, r := range inv.Records {
		if r.Host == host {
			ps[r.PackageType] = struct{}{}
			ds[r.Direction] = struct{}{}
		}
	}
	return joinSet(ps), joinSet(ds)
}

// registryDocHeader is the fixed prose of the committed docs page. The doc is
// fully generated (no hand-edited region), so a byte-comparison freshness test
// is sufficient — see TestCommittedRegistryEgressDocFresh.
const registryDocHeader = "# AICR build/CI registry egress\n\n" +
	"> Generated by `tools/registry-inventory` — do not edit by hand. " +
	"Run `make registry-docs` to regenerate.\n\n" +
	"Every package/container registry AICR's builds and CI reach out to, extracted from the\n" +
	"structured build/CI sources (recipes/registry.yaml, .settings.yaml, .goreleaser.yaml /\n" +
	".ko.yaml, Dockerfiles, .github Actions, tools/setup-tools). This host-level summary is\n" +
	"the browsable companion to the CODEOWNER-gated allowlist that gates these hosts in CI\n" +
	"(tools/registry-inventory/registry-allowlist.yaml). Transitive chart-rendered image\n" +
	"pulls are inventoried separately in the BOM (docs/user/container-images.md); the full\n" +
	"per-record inventory (image refs, pins, provenance) is produced by `make registry-inventory`.\n"

// renderDoc builds the committed docs page: a stable, host-level summary that
// changes only when the egress *surface* changes (the same trigger as the
// allowlist gate), so the freshness check stays low-churn. Per-record pins and
// versions — which churn on every bump — live only in the dist/ output.
func renderDoc(inv *Inventory) []byte {
	var b strings.Builder
	b.WriteString(registryDocHeader)

	fmt.Fprintf(&b, "\n## Distinct hosts (%d)\n\n", len(inv.Hosts))
	b.WriteString("| Host | Package types | Directions |\n|---|---|---|\n")
	hosts := append([]string(nil), inv.Hosts...)
	sort.Strings(hosts)
	for _, h := range hosts {
		pkgs, dirs := hostFacets(inv, h)
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", h, pkgs, dirs)
	}

	b.WriteString("\n## Not statically gated\n\n")
	b.WriteString("These egress surfaces are known but not host-gated — the inventory is a floor, not a ceiling:\n\n")
	for _, u := range inv.UncoveredSources {
		fmt.Fprintf(&b, "- %s\n", u)
	}
	return []byte(b.String())
}

// writeDoc writes the committed docs page.
func writeDoc(path string, inv *Inventory) error {
	if err := os.WriteFile(path, renderDoc(inv), 0o644); err != nil { //nolint:gosec // doc artifact, not a secret
		return errors.Wrap(errors.ErrCodeInternal, "write "+path, err)
	}
	return nil
}

func joinSet(m map[string]struct{}) string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return strings.Join(out, ", ")
}

// mdEscape keeps a detail string on a single, well-formed table row: newlines
// are flattened to spaces and pipes are escaped.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "|", "\\|")
}
